### ISSUE TITLE
SDK: how to add back to button in tonkeeper wallet?

### ISSUE THREAD

**Issue by LeoWangJ** [ton-connect/sdk#35]
When using TonKeeper to connect to a website with a fragment link, I found that there is a "Back to" button to return to the fragment website.

Can this feature be achieved using an SDK library? How can it be implemented? Can you give me some idea?

![截圖 2023-03-06 上午2 25 06](https://user-images.githubusercontent.com/124456163/222978654-86eccd57-b972-4846-b3ad-7eef9e3d3c2a.png)

**Comment by siandreev** [comment]
Hi @LeoWangJ ! Actually you don't need a 'Back' button in TonConnect v2. Fragment uses TonConnect v1, so Tonkeeper shows this button due to the different authorization flow. 
If you use TonConnect v2, Tonkeeper will automatically forward the user to the browser/your native app when he will press 'Connect wallet' button in the Tonkeeper
